INSERT INTO `gamevaluate`.`generaluser` (`Username`, `Email`, `Password`, `Role`, `Banned`) VALUES ('admin', 'admin@admin.it', '21232f297a57a5a743894a0e4a801fc3', '3', '0');
INSERT INTO `gamevaluate`.`generaluser` (`Username`, `Email`, `Password`, `Role`, `Banned`) VALUES ('moderator', 'mod@mod.it', 'ad148a3ca8bd0ef3b48c52454c493ec5', '2', '0');
INSERT INTO `gamevaluate`.`generaluser` (`Username`, `Email`, `Password`, `Role`, `Banned`) VALUES ('user', 'user@user.it', 'ee11cbb19052e40b07aac0ca060c23ee', '1', '0');
INSERT INTO `gamevaluate`.`genere` (`Nome`, `Descrizione`) VALUES ('FPS', 'Sparatutto in prima persone. Giochi  priincipalmente incentrati sulla guerra.');
INSERT INTO `gamevaluate`.`genere` (`Nome`, `Descrizione`) VALUES ('MOBA', 'Genere derivante dal genere MMORPG e consistente in una battaglia strategica su 3 lane, o strade.');
INSERT INTO `gamevaluate`.`genere` (`Nome`, `Descrizione`) VALUES ('Picchiaduro', 'Genere basato sul combattimento uno contro uno. I suoi punti di forza sono la conoscenza delle tecniche di combattimento e i riflessi.');
INSERT INTO `gamevaluate`.`genere` (`Nome`, `Descrizione`) VALUES ('RPG', 'Genere basao sul concetto di gioco di ruolo. I giochi di tale genere consistono in linea di massima in avventure in mondi fantastici con la possibilità di esplorare ogni anfratto e scoprire poteri nascosti.');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('Multiplatform');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('Nintendo Wiii');
<<<<<<< HEAD
=======
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('XBOX');
>>>>>>> WebsiteCode
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('PC');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('PS4');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('PS3');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('PS2');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('PSP');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('Nintendo DS');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('Game Boy');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('Nintendo Switch');
<<<<<<< HEAD
INSERT INTO `gamevaluate`.`valutazione` (`Gameplay`, `Trama`, `Grafica`, `Creativita`, `Innovazione`, `Coinvolgimento`, `Realismo`, `Rigiocabilita`, `Difficolta`) VALUES ('8', '8', '8', '8', '8', '8', '8', '8', '8');
INSERT INTO `gamevaluate`.`valutazione` (`Gameplay`, `Trama`, `Grafica`, `Creativita`, `Innovazione`, `Coinvolgimento`, `Realismo`, `Rigiocabilita`, `Difficolta`) VALUES ('8', '5', '4', '8', '9', '9', '7', '7', '7');
INSERT INTO `gamevaluate`.`valutazione` (`Gameplay`, `Trama`, `Grafica`, `Creativita`, `Innovazione`, `Coinvolgimento`, `Realismo`, `Rigiocabilita`, `Difficolta`) VALUES ('1', '2', '3', '4', '5', '6', '7', '8', '9');
INSERT INTO `gamevaluate`.`piattaforma` (`Nome`) VALUES ('XBOX');
INSERT INTO `gamevaluate`.`gioco` (`Nome`, `Descrizione`, `Genere`, `Piattaforma`, `ID_Valutazione`) VALUES ('Halo', 'Il protagonista della storia, noto come Master Chief o John-117, è un soldato geneticamente modificato facente parte del progetto SPARTAN II, creato dalle forze dell\'UNSC per proteggere le colonie del neonato impero interstellare umano ma successivamente impiegato per combattere i Covenant, un\'alleanza di razze aliene unita da una forte fede religiosa. I Covenant uccisero gran parte dei soldati SPARTAN II durante la battaglia svoltasi sul pianeta Reach; solo Master Chief riuscì a salvarsi, fuggendo nello spazio profondo a bordo dell\'astronave Pillar of Autumn del capitano Jacob Keyes per non far scoprire agli alieni la posizione della Terra, e si imbatté in un gigantesco pianeta artificiale a forma di anello.', 'FPS', 'XBOX', '1');
INSERT INTO `gamevaluate`.`gioco` (`Nome`, `Descrizione`, `Genere`, `Piattaforma`, `ID_Valutazione`) VALUES ('Monster Hunter', 'Monster Hunter permette al giocatore di impersonare un novello cacciatore che, per acquisire fama e gloria, deve completare varie missioni di caccia di altrettante varie creature. Armature, armi e altri oggetti vengono creati grazie ai resti dei mostri sconfitti, come ossa, corna o scaglie, che vengono scalcati dal giocatore. La versione online del gioco permetteva al giocatore di unirsi ad altri cacciatori (fino a un massimo di quattro) per effettuare missioni online e sconfiggere le creature più forti. Molti oggetti preziosi sono più facili da trovare online anziché offline. Il cacciatore in sé appartiene a una gilda che va a cacciare o catturare animali pericolosi per studiarli o controllare il numero, ma occasionalmente può ritrovarsi anche impegnato nel portare uova o raccogliere oggetti per medicine, se proprio è alle prime armi.', 'RPG', 'PS2', '2');
INSERT INTO `gamevaluate`.`gioco` (`Nome`, `Descrizione`, `Genere`, `Piattaforma`, `ID_Valutazione`) VALUES ('Tekken 7', 'Tekken 7 è il nuovo capitolo della storica serie picchiaduro a incontri Bandai Namco, che va a chiudere la decennale saga dei Mishima', 'Picchiaduro', 'Multiplatform', '3');
INSERT INTO `gamevaluate`.`recensione` (`Testo`, `Data`, `ID_Gioco`, `Username`) VALUES ('Gioco avvincente che spinge a superare i propri limiti in quanto a riflessi e capacità di scelta in tempo reale. Peccato per la trama lasciata un po da parte ripsetto al quadro complessivo. In linea di massima resta un ottimo gioco per gli appassionati della serie.', NOW(), '3', 'user');
=======
INSERT INTO `gamevaluate`.`valutazione` (`ID_Valutazione`,`Gameplay`, `Trama`, `Grafica`, `Creativita`, `Innovazione`, `Coinvolgimento`, `Realismo`, `Rigiocabilita`, `Difficolta`) VALUES ('1','8', '8', '8', '8', '8', '8', '8', '8', '8');
INSERT INTO `gamevaluate`.`valutazione` (`ID_Valutazione`,`Gameplay`, `Trama`, `Grafica`, `Creativita`, `Innovazione`, `Coinvolgimento`, `Realismo`, `Rigiocabilita`, `Difficolta`) VALUES ('2','8', '5', '4', '8', '9', '9', '7', '7', '7');
INSERT INTO `gamevaluate`.`valutazione` (`ID_Valutazione`,`Gameplay`, `Trama`, `Grafica`, `Creativita`, `Innovazione`, `Coinvolgimento`, `Realismo`, `Rigiocabilita`, `Difficolta`) VALUES ('3','1', '2', '3', '4', '5', '6', '7', '8', '9');
INSERT INTO `gamevaluate`.`gioco` (`Nome`, `Descrizione`, `Genere`, `Piattaforma`,`ID_Valutazione`) VALUES ('Halo', 'Il protagonista della storia, noto come Master Chief o John-117, è un soldato geneticamente modificato facente parte del progetto SPARTAN II, creato dalle forze dell\'UNSC per proteggere le colonie del neonato impero interstellare umano ma successivamente impiegato per combattere i Covenant, un\'alleanza di razze aliene unita da una forte fede religiosa. I Covenant uccisero gran parte dei soldati SPARTAN II durante la battaglia svoltasi sul pianeta Reach; solo Master Chief riuscì a salvarsi, fuggendo nello spazio profondo a bordo dell\'astronave Pillar of Autumn del capitano Jacob Keyes per non far scoprire agli alieni la posizione della Terra, e si imbatté in un gigantesco pianeta artificiale a forma di anello.', 'FPS', 'XBOX','1');
INSERT INTO `gamevaluate`.`gioco` (`Nome`, `Descrizione`, `Genere`, `Piattaforma`,`ID_Valutazione`) VALUES ('Monster Hunter', 'Monster Hunter permette al giocatore di impersonare un novello cacciatore che, per acquisire fama e gloria, deve completare varie missioni di caccia di altrettante varie creature. Armature, armi e altri oggetti vengono creati grazie ai resti dei mostri sconfitti, come ossa, corna o scaglie, che vengono scalcati dal giocatore. La versione online del gioco permetteva al giocatore di unirsi ad altri cacciatori (fino a un massimo di quattro) per effettuare missioni online e sconfiggere le creature più forti. Molti oggetti preziosi sono più facili da trovare online anziché offline. Il cacciatore in sé appartiene a una gilda che va a cacciare o catturare animali pericolosi per studiarli o controllare il numero, ma occasionalmente può ritrovarsi anche impegnato nel portare uova o raccogliere oggetti per medicine, se proprio è alle prime armi.', 'RPG', 'PS2','2');
INSERT INTO `gamevaluate`.`gioco` (`Nome`, `Descrizione`, `Genere`, `Piattaforma`,`ID_Valutazione`) VALUES ('Tekken 7', 'Tekken 7 è il nuovo capitolo della storica serie picchiaduro a incontri Bandai Namco, che va a chiudere la decennale saga dei Mishima', 'Picchiaduro', 'Multiplatform','3');
>>>>>>> WebsiteCode
